# .github/workflows/audit.yml

name: Scrape and Audit Content

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'config.json'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9 with dependency caching
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: python scripts/scrape.py

      - name: Run linting script
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: python scripts/lint.py

      - name: Upload scraped markdown as artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-markdown-files
          path: scraped/

      - name: Upload audit report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: report.json
      
      - name: Commit report and scraped files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update audit report and scraped markdown"
          # This pattern tells the action to commit the report and the entire scraped/ directory
          file_pattern: "report.json scraped/"
