# .github/workflows/audit.yml

name: Scrape and Audit Content

on:
  # Allows for manual triggering of the workflow from the GitHub Actions tab
  workflow_dispatch:

  # Triggers the workflow on pushes to the main branch, but only if config.json was changed
  push:
    branches:
      - main
    paths:
      - 'config.json'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Download spaCy English model
        run: python -m spacy download en_core_web_sm

      - name: Run scraping script
        run: python scripts/scrape.py

      # --- DEBUGGING STEP ADDED HERE ---
      - name: List files after scraping
        run: ls -R

      - name: Run linting script
        env:
          # Pass GitHub context variables to the linting script to build permalinks
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: python scripts/lint.py

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: report.json
